// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBlAdAP_DIaK2AD4XQr-5RbisjXyTNUm8',
    appId: '1:295047297313:web:619c76ce683d7701a0a660',
    messagingSenderId: '295047297313',
    projectId: 'virtualshopping-6918d',
    authDomain: 'virtualshopping-6918d.firebaseapp.com',
    storageBucket: 'virtualshopping-6918d.appspot.com',
    measurementId: 'G-2H7ZVXGDFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEOLGXy4BtHwJOpVTwJFLHFiqI6XUJhI',
    appId: '1:295047297313:android:cce212c7f8a48b78a0a660',
    messagingSenderId: '295047297313',
    projectId: 'virtualshopping-6918d',
    storageBucket: 'virtualshopping-6918d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5YUnMcR9AZ-ywpmsGct-DpD4_xkWhr4',
    appId: '1:295047297313:ios:7947fd9cf228298aa0a660',
    messagingSenderId: '295047297313',
    projectId: 'virtualshopping-6918d',
    storageBucket: 'virtualshopping-6918d.appspot.com',
    iosBundleId: 'com.example.virtualShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy5YUnMcR9AZ-ywpmsGct-DpD4_xkWhr4',
    appId: '1:295047297313:ios:81d9aa0444682feba0a660',
    messagingSenderId: '295047297313',
    projectId: 'virtualshopping-6918d',
    storageBucket: 'virtualshopping-6918d.appspot.com',
    iosBundleId: 'com.example.virtualShoppingApp.RunnerTests',
  );
}
